port: 8080
db:
        driver: sqlite3
        source: ":memory:"
# Use regular expressions
allowed_sites: 
        - domain: ".*"
          paths:
                - ".*"
# In minutes
challenge_timeout: 2 