package main

import (
	"flag"
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
)

const fileHeader = `
// DO NOT edit this file
// this file was generated automatically
// simply run ` + "`" + `go generate` + "`" + ` in this directory to regenerate

package res

import (
	"fmt"
	"html/template"
)

var (
	Template = template.New("")
	Styles = make(map[string][]byte, 0)
)

func genInit() {
	var err error
`

const templateDecl = `
	_, err = Template.Parse(%#[2]v)
	if err != nil {
		panic(fmt.Sprintf("error parsing %[1]s - %%v", err))
	}
`

const styleDecl = `
	Styles[%#v] = []byte(%#v)
`
const fileFooter = `
}
// end of generated file
`

const (
	outFileName  = "res_gen.go"
	outFileFlags = os.O_CREATE | os.O_WRONLY | os.O_TRUNC
	outFilePerms = 0660
)

var (
	outFile *os.File
	dataDir string
)

func panicIf(err error) {
	if err != nil {
		panic(err)
	}
}

func genGoFile(fPath string, info os.FileInfo, err error) error {
	panicIf(err)
	if info.IsDir() {
		return nil
	}
	normPath, err := filepath.Rel(dataDir, fPath)
	panicIf(err)
	switch filepath.Ext(normPath) {
	case ".tmpl":
		b, err := ioutil.ReadFile(fPath)
		panicIf(err)
		fmt.Fprintf(outFile, templateDecl, normPath, string(b))
	case ".css":
		b, err := ioutil.ReadFile(fPath)
		panicIf(err)
		fmt.Fprintf(outFile, styleDecl, normPath, string(b))
	}
	return nil
}

func main() {
	var err error
	flag.Parse()
	dataDir = strings.TrimSpace(flag.Arg(0))
	panicIf(err)
	outFile, err = os.OpenFile(outFileName, outFileFlags, outFilePerms)
	panicIf(err)
	defer outFile.Close()
	fmt.Fprint(outFile, fileHeader)
	filepath.Walk("./data/", genGoFile)
	fmt.Fprint(outFile, fileFooter)
}
